const getBlueDecks = {
  cards: [
    {
      name: "draw",
      description: "test card 1",
      levels: 1,
      abilityCosts: [2],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 2",
      levels: 2,
      abilityCosts: [4],
      abilityType: "WHENDESTROYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 3",
      levels: 1,
      abilityCosts: [6],
      abilityType: "ONPLAYERTURN",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 4",
      levels: 3,
      abilityCosts: [2],
      abilityType: "WHENDESTROYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 5",
      levels: 1,
      abilityCosts: [4],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 6",
      levels: 1,
      abilityCosts: [6],
      abilityType: "ONOPPONENTTURN",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 7",
      levels: 1,
      abilityCosts: [2],
      abilityType: "ONOPPONENTTURN",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 8",
      levels: 2,
      abilityCosts: [4],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 9",
      levels: 3,
      abilityCosts: [6],
      abilityType: "ONBOTHTURNS",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 10",
      levels: 1,
      abilityCosts: [2],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 11",
      levels: 1,
      abilityCosts: [4],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 12",
      levels: 2,
      abilityCosts: [6],
      abilityType: "ONACTIVATE",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 13",
      levels: 1,
      abilityCosts: [2],
      abilityType: "ONACTIVATE",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 14",
      levels: 3,
      abilityCosts: [4],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 15",
      levels: 1,
      abilityCosts: [6],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 16",
      levels: 2,
      abilityCosts: [2],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 17",
      levels: 3,
      abilityCosts: [4],
      abilityType: "ONACTIVATE",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 18",
      levels: 1,
      abilityCosts: [6],
      abilityType: "WHENPLAYED",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
    {
      name: "draw",
      description: "test card 19",
      levels: 2,
      abilityCosts: [2],
      abilityType: "ONBOTHTURNS",
      cardTypesAllowed: ["Hire", "Lead"],
    },
    {
      name: "discard",
      description: "test card 20",
      levels: 3,
      abilityCosts: [4],
      abilityType: "ONACTIVATE",
      cardTypesAllowed: ["Wares", "Hustles", "Circumstances"],
    },
  ],
};

export default getBlueDecks;
